# Generated by Django 3.1.1 on 2020-09-27 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリー名')),
                ('url_code', models.CharField(max_length=50, null=True, unique=True, verbose_name='URLコード')),
                ('sort', models.IntegerField(default=0, verbose_name='ソート')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('no', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=30, null=True, verbose_name='お名前')),
                ('message', models.TextField(verbose_name='投稿内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='投稿画像')),
                ('pub_flg', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IPアドレス')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('user_name', models.CharField(max_length=30, null=True, verbose_name='お名前')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('message', models.TextField(null=True, verbose_name='本文')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='room.category', verbose_name='カテゴリー')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='room.topic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
